server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: Always

logging:
  level:
    com.ead: TRACE
    root: INFO
    org:
      hibernate: INFO
      springframework:
        web: DEBUG
